development:
  # Database
  DATABASE_ADAPTER: postgresql
  DATABASE_USER: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_NAME: commerce_development
  DATABASE_HOST: localhost
  STRIPE_PK: pk_test_8Bp5SPYUPuvp11paRdVGrzm000VVDMoiNv
  STRIPE_SK: sk_test_ENH1bLiUS6FCKydf0FQXYEQ500ggZakkHB
  STRIPE_CLIENT_ID: ca_CefKAEpsiwJZKJMW6mc98sgbjIjV8dPI

production:
  # Database
  DATABASE_ADAPTER: postgresql
  DATABASE_USER: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_NAME: commerces_production
  DATABASE_HOST: localhost
  STRIPE_PK: pk_test_8Bp5SPYUPuvp11paRdVGrzm000VVDMoiNv
  STRIPE_SK: sk_test_ENH1bLiUS6FCKydf0FQXYEQ500ggZakkHB
  STRIPE_CLIENT_ID: ca_CefKAEpsiwJZKJMW6mc98sgbjIjV8dPI
